# Generated by Django 6.0.2 on 2026-03-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('CLOTHES', 'Clothes'), ('TOYS', 'Toys'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items')),
                ('description', models.TextField(blank=True)),
                ('pickup_location', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='donations.physicaldonation')),
            ],
        ),
    ]
